"""add provider clicks

Revision ID: 0b82c2271300
Revises: ea769f4af31c
Create Date: 2026-05-29 15:57:54.489340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b82c2271300'
down_revision: Union[str, None] = 'ea769f4af31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('from_currency', sa.String(), nullable=False),
    sa.Column('to_currency', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_clicks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_clicks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_clicks_provider'), ['provider'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('university',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('university',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('provider_clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_clicks_provider'))
        batch_op.drop_index(batch_op.f('ix_provider_clicks_id'))

    op.drop_table('provider_clicks')
    # ### end Alembic commands ###
