"""initial schema

Revision ID: ea769f4af31c
Revises: 
Create Date: 2026-05-08 20:14:59.005967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea769f4af31c'
down_revision: Union[str, None] = '0001_create_initial_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('home_currency', sa.String(), nullable=True))
    op.add_column('users', sa.Column('corridor_from', sa.String(), nullable=True))
    op.add_column('users', sa.Column('corridor_to', sa.String(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'university',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'university',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'corridor_to')
    op.drop_column('users', 'corridor_from')
    op.drop_column('users', 'home_currency')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
