// 30 major currencies used across the Flint compare widget
export const CURRENCIES = [
  { code: "USD", name: "US Dollar",             flag: "🇺🇸" },
  { code: "GBP", name: "British Pound",          flag: "🇬🇧" },
  { code: "EUR", name: "Euro",                   flag: "🇪🇺" },
  { code: "INR", name: "Indian Rupee",           flag: "🇮🇳" },
  { code: "CAD", name: "Canadian Dollar",        flag: "🇨🇦" },
  { code: "AUD", name: "Australian Dollar",      flag: "🇦🇺" },
  { code: "AED", name: "UAE Dirham",             flag: "🇦🇪" },
  { code: "SGD", name: "Singapore Dollar",       flag: "🇸🇬" },
  { code: "JPY", name: "Japanese Yen",           flag: "🇯🇵" },
  { code: "CNY", name: "Chinese Yuan",           flag: "🇨🇳" },
  { code: "CHF", name: "Swiss Franc",            flag: "🇨🇭" },
  { code: "MYR", name: "Malaysian Ringgit",      flag: "🇲🇾" },
  { code: "PHP", name: "Philippine Peso",        flag: "🇵🇭" },
  { code: "PKR", name: "Pakistani Rupee",        flag: "🇵🇰" },
  { code: "BDT", name: "Bangladeshi Taka",       flag: "🇧🇩" },
  { code: "NGN", name: "Nigerian Naira",         flag: "🇳🇬" },
  { code: "KES", name: "Kenyan Shilling",        flag: "🇰🇪" },
  { code: "GHS", name: "Ghanaian Cedi",          flag: "🇬🇭" },
  { code: "ZAR", name: "South African Rand",     flag: "🇿🇦" },
  { code: "MXN", name: "Mexican Peso",           flag: "🇲🇽" },
  { code: "BRL", name: "Brazilian Real",         flag: "🇧🇷" },
  { code: "THB", name: "Thai Baht",              flag: "🇹🇭" },
  { code: "IDR", name: "Indonesian Rupiah",      flag: "🇮🇩" },
  { code: "VND", name: "Vietnamese Dong",        flag: "🇻🇳" },
  { code: "HKD", name: "Hong Kong Dollar",       flag: "🇭🇰" },
  { code: "NZD", name: "New Zealand Dollar",     flag: "🇳🇿" },
  { code: "SAR", name: "Saudi Riyal",            flag: "🇸🇦" },
  { code: "QAR", name: "Qatari Riyal",           flag: "🇶🇦" },
  { code: "KWD", name: "Kuwaiti Dinar",          flag: "🇰🇼" },
  { code: "TRY", name: "Turkish Lira",           flag: "🇹🇷" },
];

/** Map of country ISO code → default home currency */
export const COUNTRY_CURRENCY_MAP = {
  IN: "INR", AU: "AUD", US: "USD", GB: "GBP", CA: "CAD",
  DE: "EUR", FR: "EUR", NL: "EUR", IE: "EUR", SG: "SGD",
  NZ: "NZD", AE: "AED", JP: "JPY", CN: "CNY", CH: "CHF",
  MY: "MYR", PH: "PHP", PK: "PKR", BD: "BDT", NG: "NGN",
  KE: "KES", GH: "GHS", ZA: "ZAR", MX: "MXN", BR: "BRL",
  TH: "THB", ID: "IDR", VN: "VND", HK: "HKD", SA: "SAR",
  QA: "QAR", KW: "KWD", TR: "TRY",
};
