// University database grouped by country
// Each entry has: name, city (optional), country code

export const COUNTRIES = [
  { code: "IN", name: "India", flag: "🇮🇳" },
  { code: "AU", name: "Australia", flag: "🇦🇺" },
  { code: "US", name: "United States", flag: "🇺🇸" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧" },
  { code: "CA", name: "Canada", flag: "🇨🇦" },
  { code: "DE", name: "Germany", flag: "🇩🇪" },
  { code: "SG", name: "Singapore", flag: "🇸🇬" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿" },
  { code: "IE", name: "Ireland", flag: "🇮🇪" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱" },
  { code: "FR", name: "France", flag: "🇫🇷" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪" },
];

export const UNIVERSITIES = {
  IN: [
    { name: "BITS Pilani, Hyderabad Campus", city: "Hyderabad" },
    { name: "BITS Pilani, Goa Campus", city: "Goa" },
    { name: "BITS Pilani, Pilani Campus", city: "Pilani" },
    { name: "Indian Institute of Technology Bombay", city: "Mumbai" },
    { name: "Indian Institute of Technology Delhi", city: "New Delhi" },
    { name: "Indian Institute of Technology Madras", city: "Chennai" },
    { name: "Indian Institute of Technology Kanpur", city: "Kanpur" },
    { name: "Indian Institute of Technology Kharagpur", city: "Kharagpur" },
    { name: "Indian Institute of Science", city: "Bangalore" },
    { name: "Delhi University", city: "New Delhi" },
    { name: "Jawaharlal Nehru University", city: "New Delhi" },
    { name: "University of Hyderabad", city: "Hyderabad" },
    { name: "Manipal Academy of Higher Education", city: "Manipal" },
    { name: "Vellore Institute of Technology", city: "Vellore" },
    { name: "SRM Institute of Science and Technology", city: "Chennai" },
    { name: "Amity University", city: "Noida" },
  ],
  AU: [
    { name: "RMIT University", city: "Melbourne" },
    { name: "University of Melbourne", city: "Melbourne" },
    { name: "University of Sydney", city: "Sydney" },
    { name: "Australian National University", city: "Canberra" },
    { name: "University of Queensland", city: "Brisbane" },
    { name: "University of New South Wales", city: "Sydney" },
    { name: "Monash University", city: "Melbourne" },
    { name: "University of Western Australia", city: "Perth" },
    { name: "University of Adelaide", city: "Adelaide" },
    { name: "University of Technology Sydney", city: "Sydney" },
    { name: "Macquarie University", city: "Sydney" },
    { name: "Deakin University", city: "Geelong" },
    { name: "Curtin University", city: "Perth" },
    { name: "Queensland University of Technology", city: "Brisbane" },
  ],
  US: [
    { name: "University at Buffalo", city: "Buffalo, NY" },
    { name: "University of Iowa", city: "Iowa City, IA" },
    { name: "Concordia University, St. Paul", city: "St. Paul, MN" },
    { name: "Rensselaer Polytechnic Institute", city: "Troy, NY" },
    { name: "Massachusetts Institute of Technology", city: "Cambridge, MA" },
    { name: "Stanford University", city: "Stanford, CA" },
    { name: "Harvard University", city: "Cambridge, MA" },
    { name: "California Institute of Technology", city: "Pasadena, CA" },
    { name: "University of California, Berkeley", city: "Berkeley, CA" },
    { name: "University of Michigan", city: "Ann Arbor, MI" },
    { name: "Georgia Institute of Technology", city: "Atlanta, GA" },
    { name: "Carnegie Mellon University", city: "Pittsburgh, PA" },
    { name: "Columbia University", city: "New York, NY" },
    { name: "University of Illinois Urbana-Champaign", city: "Champaign, IL" },
    { name: "New York University", city: "New York, NY" },
    { name: "University of California, Los Angeles", city: "Los Angeles, CA" },
    { name: "Purdue University", city: "West Lafayette, IN" },
    { name: "University of Texas at Austin", city: "Austin, TX" },
    { name: "University of Southern California", city: "Los Angeles, CA" },
    { name: "Arizona State University", city: "Tempe, AZ" },
    { name: "University of Florida", city: "Gainesville, FL" },
    { name: "Northeastern University", city: "Boston, MA" },
    { name: "University of Washington", city: "Seattle, WA" },
    { name: "University of Wisconsin-Madison", city: "Madison, WI" },
  ],
  GB: [
    { name: "University of Oxford", city: "Oxford" },
    { name: "University of Cambridge", city: "Cambridge" },
    { name: "Imperial College London", city: "London" },
    { name: "University College London", city: "London" },
    { name: "London School of Economics", city: "London" },
    { name: "University of Edinburgh", city: "Edinburgh" },
    { name: "University of Manchester", city: "Manchester" },
    { name: "King's College London", city: "London" },
    { name: "University of Warwick", city: "Coventry" },
    { name: "University of Bristol", city: "Bristol" },
    { name: "University of Glasgow", city: "Glasgow" },
    { name: "University of Birmingham", city: "Birmingham" },
    { name: "University of Leeds", city: "Leeds" },
    { name: "University of Sheffield", city: "Sheffield" },
  ],
  CA: [
    { name: "University of Toronto", city: "Toronto" },
    { name: "University of British Columbia", city: "Vancouver" },
    { name: "McGill University", city: "Montreal" },
    { name: "University of Waterloo", city: "Waterloo" },
    { name: "University of Alberta", city: "Edmonton" },
    { name: "McMaster University", city: "Hamilton" },
    { name: "University of Ottawa", city: "Ottawa" },
    { name: "Simon Fraser University", city: "Burnaby" },
    { name: "University of Calgary", city: "Calgary" },
    { name: "Western University", city: "London" },
    { name: "Concordia University", city: "Montreal" },
    { name: "Carleton University", city: "Ottawa" },
  ],
  DE: [
    { name: "Technical University of Munich", city: "Munich" },
    { name: "Ludwig Maximilian University", city: "Munich" },
    { name: "Heidelberg University", city: "Heidelberg" },
    { name: "Humboldt University of Berlin", city: "Berlin" },
    { name: "Free University of Berlin", city: "Berlin" },
    { name: "RWTH Aachen University", city: "Aachen" },
    { name: "University of Freiburg", city: "Freiburg" },
    { name: "University of Tübingen", city: "Tübingen" },
    { name: "University of Göttingen", city: "Göttingen" },
    { name: "TU Berlin", city: "Berlin" },
  ],
  SG: [
    { name: "National University of Singapore", city: "Singapore" },
    { name: "Nanyang Technological University", city: "Singapore" },
    { name: "Singapore Management University", city: "Singapore" },
    { name: "Singapore University of Technology and Design", city: "Singapore" },
    { name: "Singapore Institute of Technology", city: "Singapore" },
  ],
  NZ: [
    { name: "University of Auckland", city: "Auckland" },
    { name: "University of Otago", city: "Dunedin" },
    { name: "Victoria University of Wellington", city: "Wellington" },
    { name: "University of Canterbury", city: "Christchurch" },
    { name: "Massey University", city: "Palmerston North" },
    { name: "University of Waikato", city: "Hamilton" },
  ],
  IE: [
    { name: "Trinity College Dublin", city: "Dublin" },
    { name: "University College Dublin", city: "Dublin" },
    { name: "National University of Ireland Galway", city: "Galway" },
    { name: "University College Cork", city: "Cork" },
    { name: "Dublin City University", city: "Dublin" },
    { name: "University of Limerick", city: "Limerick" },
  ],
  NL: [
    { name: "University of Amsterdam", city: "Amsterdam" },
    { name: "Delft University of Technology", city: "Delft" },
    { name: "Erasmus University Rotterdam", city: "Rotterdam" },
    { name: "Leiden University", city: "Leiden" },
    { name: "Utrecht University", city: "Utrecht" },
    { name: "Eindhoven University of Technology", city: "Eindhoven" },
    { name: "Wageningen University", city: "Wageningen" },
    { name: "University of Groningen", city: "Groningen" },
  ],
  FR: [
    { name: "Sorbonne University", city: "Paris" },
    { name: "École Polytechnique", city: "Palaiseau" },
    { name: "Sciences Po", city: "Paris" },
    { name: "University of Paris-Saclay", city: "Paris" },
    { name: "École Normale Supérieure", city: "Paris" },
    { name: "HEC Paris", city: "Jouy-en-Josas" },
    { name: "INSEAD", city: "Fontainebleau" },
    { name: "University of Strasbourg", city: "Strasbourg" },
  ],
  AE: [
    { name: "Khalifa University", city: "Abu Dhabi" },
    { name: "United Arab Emirates University", city: "Al Ain" },
    { name: "American University of Sharjah", city: "Sharjah" },
    { name: "University of Sharjah", city: "Sharjah" },
    { name: "New York University Abu Dhabi", city: "Abu Dhabi" },
    { name: "Heriot-Watt University Dubai", city: "Dubai" },
    { name: "BITS Pilani, Dubai Campus", city: "Dubai" },
  ],
};

/**
 * Filter universities for a given country code, with optional search term
 */
export function getUniversities(countryCode, searchTerm = "") {
  const list = UNIVERSITIES[countryCode] || [];
  if (!searchTerm.trim()) return list;
  const q = searchTerm.toLowerCase();
  return list.filter(
    (u) =>
      u.name.toLowerCase().includes(q) ||
      (u.city && u.city.toLowerCase().includes(q))
  );
}
